name: Deploy CDK App (TypeScript)

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  DeployCDKApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install -g aws-cdk
      
      - name: Configure AWS Credentials
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          # Download and configure IAM Roles Anywhere signing helper
          curl -LO https://rolesanywhere.amazonaws.com/releases/1.2.1/X86_64/Linux/aws_signing_helper
          chmod +x aws_signing_helper
          
          # Create certificate and key files
          printf "%s" "$CERTIFICATE" > certificate.txt
          printf "%s" "$PRIVATE_KEY" > private_key.pem
          
          # Generate temporary credentials using IAM Roles Anywhere
          ./aws_signing_helper credential-process --certificate certificate.txt --private-key private_key.pem --trust-anchor-arn ${{ vars.TRUST_ANCHOR_ARN }} --profile-arn ${{ vars.PROFILE_ARN }} --role-arn ${{ vars.role_arn }} > aws_credentials.json

          # Export credentials as environment variables
          export AWS_ACCESS_KEY_ID=$(jq -r '.AccessKeyId' aws_credentials.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r '.SecretAccessKey' aws_credentials.json)
          export AWS_SESSION_TOKEN=$(jq -r '.SessionToken' aws_credentials.json)

          # Get AWS Account ID dynamically and set as environment variable
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "AWS_ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
          echo "CDK_DEFAULT_ACCOUNT=$ACCOUNT_ID" >> $GITHUB_ENV
          echo "CDK_DEFAULT_REGION=$AWS_REGION" >> $GITHUB_ENV

      - name: Build TypeScript
        run: npm run build
      
      - name: CDK Synth
        run: cdk synth
      
      - name: CDK Deploy
        run: cdk deploy --all --require-approval never
